# ---- Model Configuration ----

name: YOLO

server:
  cut-layer: a            # Partition point: a / b / c / d
  clients:
    - 1
    - 1
  model: yolo11n
  batch-frame: 5          # Number of frames processed per batch


# ---- RabbitMQ Configuration ----

rabbit:
#  address: 127.0.0.1
#  username: guest
#  password: guest

  # Remote setup (example)
   address: "192.168.101.91"
   username: "dai"
   password: "dai"

  virtual-host: /
  queue_device_1: "device1"
  queue_device_2: "device2"


# ---- Input / Output ----

data: videos/video.mp4    # Input video path
log-path: res             # Output directory for logs/results
control-count: 10         # Control signal frequency (used for synchronization)
debug-mode: False         # Enable debug logging


# ---- Compression ----

compress:
  enable: True
  num_bit: 8              # Quantization bit-width


# ---- mAP Evaluation ----

cal_map:
  enable: False
  create_label: False     # Generate ground-truth labels


# ---- Tracker ----

tracker:
  enable: False
  FPS: 30                 # Target display FPS


# ---- Layer Timing ----

time_layer:
  num_round: 5            # Number of runs for averaging
  input_shape: [1, 3, 640, 640]


# ---- Partition Strategy ----

partition:
  auto: True             # True → auto-select cut layer
  re-measure: True       # True → recompute latency instead of using cached results


# ---- Clustering  ----

clustering:
  num_clusters: 1         # 0 → automatically find optimal K
  max_iterations: 500     # Max iterations for K-means
  num_runs: 20            # Number of runs for silhouette score

  # Feature weights:
  # [compute, RAM, network, storage]
  weights: [1.4, 1.2, 1.1, 0.65]